name: Label & comment issues #the name of the workflow
on:
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request:
    types:
      - opened

jobs:
  label_and_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      # 1. Leimojen lisäys (Vain kun ISSUE avataan)
      - name: attach label to issues
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      # 2. Tervetulokommentti (Vain kun ISSUE avataan)
      - name: Comment on new issue
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for opening this issue! We'll take a look as soon as possible."
            })

      # 3. OPISKELIJA 2: Automaattinen kommentti kun ISSUE suljetaan
      - name: Comment on closed issue
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The issue is now resolved.'
            })

      # 4. OPISKELIJA 3: Onnitteluviesti kun uusi PR avataan
      - name: Congratulate on PR
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Congratulations on opening your first Pull Request! '
            })
